// Code generated by sqlc. DO NOT EDIT.
// source: badge.sql

package db

import (
	"context"
)

const createBadge = `-- name: CreateBadge :one
INSERT INTO badge (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateBadge(ctx context.Context, name string) (Badge, error) {
	row := q.db.QueryRowContext(ctx, createBadge, name)
	var i Badge
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
