// Code generated by sqlc. DO NOT EDIT.
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (author, post_id, body)
VALUES ($1, $2, $3)
RETURNING id, post_id, body, created_at, author
`

type CreateCommentParams struct {
	Author string `json:"author"`
	PostID int64  `json:"post_id"`
	Body   string `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Author, arg.PostID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Body,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}
