// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID        int64     `json:"id"`
	Author    string    `json:"author"`
	PostID    int64     `json:"post_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Follow struct {
	ID          int64 `json:"id"`
	FollowingID int64 `json:"following_id"`
	FollowerID  int64 `json:"follower_id"`
}

type Note struct {
	ID        int64     `json:"id"`
	Author    string    `json:"author"`
	PostID    int64     `json:"post_id"`
	Body      string    `json:"body"`
	Page      int16     `json:"page"`
	Line      int16     `json:"line"`
	CreatedAt time.Time `json:"created_at"`
}

type Post struct {
	ID           int64     `json:"id"`
	Author       string    `json:"author"`
	Title        string    `json:"title"`
	BookAuthor   string    `json:"book_author"`
	BookImage    string    `json:"book_image"`
	BookPage     int16     `json:"book_page"`
	BookPageRead int16     `json:"book_page_read"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PostCategory struct {
	ID         int64 `json:"id"`
	PostID     int64 `json:"post_id"`
	CategoryID int64 `json:"category_id"`
}

type PostFavorite struct {
	ID     int64 `json:"id"`
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

type Transfer struct {
	ID         int64     `json:"id"`
	FromUserID int64     `json:"from_user_id"`
	ToUserID   int64     `json:"to_user_id"`
	Amount     int64     `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	Profile           string    `json:"profile"`
	Image             string    `json:"image"`
	Points            int64     `json:"points"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
