// Code generated by sqlc. DO NOT EDIT.
// source: notes.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (author, post_id, body, page, line)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author, post_id, body, page, line, created_at
`

type CreateNoteParams struct {
	Author string `json:"author"`
	PostID int64  `json:"post_id"`
	Body   string `json:"body"`
	Page   int16  `json:"page"`
	Line   int16  `json:"line"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Author,
		arg.PostID,
		arg.Body,
		arg.Page,
		arg.Line,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.PostID,
		&i.Body,
		&i.Page,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}
