// Code generated by sqlc. DO NOT EDIT.
// source: post_favorite.sql

package db

import (
	"context"
)

const createPostFavorite = `-- name: CreatePostFavorite :one
INSERT INTO post_favorites (post_id, user_id)
VALUES ($1, $2)
RETURNING id, post_id, user_id
`

type CreatePostFavoriteParams struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CreatePostFavorite(ctx context.Context, arg CreatePostFavoriteParams) (PostFavorite, error) {
	row := q.db.QueryRowContext(ctx, createPostFavorite, arg.PostID, arg.UserID)
	var i PostFavorite
	err := row.Scan(&i.ID, &i.PostID, &i.UserID)
	return i, err
}
