// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostCategory(ctx context.Context, arg CreatePostCategoryParams) (PostCategory, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountByOwner(ctx context.Context, owner string) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetPostCategory(ctx context.Context, postID int64) (Category, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserImage(ctx context.Context, username string) (string, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListMyPosts(ctx context.Context, arg ListMyPostsParams) ([]Post, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdatePostCategory(ctx context.Context, arg UpdatePostCategoryParams) (PostCategory, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
